@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(customer, "Customer")

System_Boundary(system, "NovaMarket") {

    Container(api, "API Gateway", "NGINX", "Входная точка")

    Container(order, "Order Service", "Kotlin", "Создание заказов (write)")
    Container(inventory, "Inventory Service", "Kotlin", "Резервы")
    Container(payment, "Payment Service", "Kotlin", "Оплата")
    Container(delivery, "Delivery Service", "Kotlin", "Доставка")

    Container(kafka, "Kafka", "Event Broker", "События")

    Container(query, "Order Query Service", "Kotlin", "Чтение истории заказов")
    ContainerDb(read_db, "Read DB", "PostgreSQL / NoSQL", "Денормализованная модель")
}

Rel(customer, api, "HTTP")

Rel(api, order, "REST (write)")
Rel(api, query, "REST (read)")

Rel(order, kafka, "publishes")
Rel(inventory, kafka, "publishes")
Rel(payment, kafka, "publishes")
Rel(delivery, kafka, "publishes")

Rel(kafka, query, "consumes events")

Rel(query, read_db, "reads/writes")

@enduml